zero-page section flag
johnwbyrd/llvm-mos pull request #5
Opened 2020-09-11 11:32 UTC by laoo

As a follow-up of a [forum duscussion](http://forum.6502.org/viewtopic.php?f=2&t=6241&start=15#p78182) I've prepared a minimal proposal for zero-page section flag.
It's a pull request, but I don't insist on pulling it. It's just a proof of concept.

pros:
- it works
- it permits to have multiple different sections on page zero with different semantics
- it's not a precedence. There is already for example flag `SHF_ARM_PURECODE` with flag letter "y"

cons:
LLVM architecture is poorly suited to such actions and it must be done globally. E.g. the 'z' flag that I've used will work for any other machine as ElfArmParser does not check triples and does not forward unknown flags to target parsers. And vice versa - other flags for other machines can be interpreted as `SHF_MOS_ZEROPAGE` in MOSBackend if it happens to use the same bit. It can be easily done that way but in other places flags are treated globally too and handling it in implementations of specific machines needs heavy lifting.

2020-09-12 21:33 UTC, johnwbyrd requested changes
Some improvements requested below.

2020-09-12 21:33 UTC, johnwbyrd commented on llvm/include/llvm/BinaryFormat/ELF.h
> +  SHF_MOS_ZEROPAGE = 0x10000000
I think this should be 0x01000000 to be consistent with the rest of the constants...

2020-09-12 21:33 UTC, johnwbyrd commented on llvm/test/MC/MOS/zeropage.s
> +  .text
This test doesn't actually exercise both halves of the code path and check for expected outputs.  I'd really like to see proper test cases for this patch.  See some of the other examples in this directory for ideas how to do this.

2020-09-12 21:35 UTC, johnwbyrd commented
I just wanted to add that you're clearly a very skilled programmer and I welcome your help on this project.

2020-09-14 10:20 UTC, laoo commented
The more I think about it, it seems to me that the `parseSectionFlags` function in `ELFAsmParser.cpp` is buggy. It clearly should not be allowed to use section flags from different targets. For example my 'z' flag coincidentally uses the same bit as 'd' flag which is defined as `XCORE_SHF_DP_SECTION`. As it is correct to reuse bits (as there is a `SHF_MASKPROC` mask reserving bits for processor-specific flags) it's incorrect to set these bits unintentionally. Maybe it would be reasonable to propose some solution to LLVM and to build MOS' zero-page flag on that, given it would be accepted.

2020-09-14 20:17 UTC, johnwbyrd commented
This pull request may be submitted yet.  I think that LLVM might have broken the naming-based zero page system I built before this.  The proof will be in a proper test suite that exercises all the modifiers and zero page naming methods.  I'd love to see one if you have the time -- otherwise I'll write one when I get to it.

2020-09-18 15:12 UTC, laoo commented on llvm/include/llvm/BinaryFormat/ELF.h
> +  SHF_MOS_ZEROPAGE = 0x10000000
https://github.com/johnwbyrd/llvm-mos/blob/216efa94536c0e86cf2c123be817cc583e955b83/llvm/include/llvm/BinaryFormat/ELF.h#L960-L965

Taking into account these two masks I am using the value that is masked by `SHF_MASKPROC`. Do you think that the other one should be used?

2020-09-18 16:23 UTC, laoo commented
I've worked a little on this when finally had some time but this huge rebase gave me a headache when I was trying to embrace the changes. This pull request is to the old branch and gives some conflicts. So maybe I'll do the following:
- open a new feature request regarding adding this zero-page section flag,
- add a new pull request to the new rebased code-base.

2020-09-18 17:01 UTC, closed without merging

2020-09-24 21:57 UTC, johnwbyrd commented
I'm sorry about that, but the rebase was the long term fix for the MSVC compilation bug you mentioned.  I can take a crack at that rebase in time, if you like.

2020-09-25 06:35 UTC, laoo commented
It took me few hours but I managed :) I just had no experience with synchronizing github forks.
I have a formal question though: what are the customs with contributing code? Just create sole pull-request or create an issue (something like feature request) and then attach a pull-request to it? I am thinking about few things that I could propose.
The other question - what work do you see that needs to be done inside the assembler? I could try dig into it.